import os

ENVIRONMENT = os.environ['ENVIRONMENT']
APPLICATION_NAME = os.environ['APPLICATION_NAME']
AUTHORIZATION_HEADER = "Authorization"
EXPIRATION_DELAY_IN_DAYS = 7
WEBSITE_HOSTNAME = os.environ['WEBSITE_HOSTNAME']
