name: hallebarde application

on: [push]

jobs:
  tests-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install system dependencies
        run: |
          sudo apt-get -q update && sudo apt-get -y -q install make && sudo rm -rf /var/lib/apt/lists/*
          python -m pip install --quiet --upgrade pip
          pip install --quiet pipenv==2018.11.26
      - name: Install dependencies
        run: pipenv install --dev
      - name: Measure quality with mypy & flake8
        run: make -C app/ quality_checks
      - name: Run security checks with bandit & safety
        run: make -C app/ security_checks
      - name: Run unit tests and measure code coverage
        run: make -C app/ unit_tests

  tests-frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm --version
      - run: make -C hallebarde-frontend/ install-dependencies
      - run: make -C hallebarde-frontend/ tests-with-coverage

  build:
    needs: tests-backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install system dependencies
        run: |
          sudo apt-get -q update && \
            sudo apt-get -y -q install make unzip wget && \
            sudo rm -rf /var/lib/apt/lists/*
          python -m pip install --quiet --upgrade pip && \
            pip install --quiet pipenv==2018.11.26
          wget https://releases.hashicorp.com/terraform/0.12.23/terraform_0.12.23_linux_386.zip && \
            unzip terraform_0.12.23_linux_386.zip && \
            rm terraform_0.12.23_linux_386.zip && \
            sudo mv ./terraform /usr/local/bin && \
            terraform --version
          wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.23.31/terragrunt_linux_amd64 && \
            sudo mv ./terragrunt_linux_amd64 /usr/local/bin/terragrunt && chmod +x /usr/local/bin/terragrunt && \
            terragrunt --version
      - name: Package the application
        run: make -C app/ package
      - name: Lint infrastructure code
        run: export AWS_REGION="eu-west-1" && make -C deploy/ lint
